apiVersion: v1
kind: Service
metadata:
  name: backforge-api
  namespace: backforge
spec:
  type: ClusterIP
  selector:
    app: backforge-api
  ports:
    - name: http
      port: 80
      targetPort: http
