apiVersion: v1
kind: Service
metadata:
  name: backforge-api-canary
  labels:
    app.kubernetes.io/name: backforge-api
    app.kubernetes.io/component: canary-service
    app.kubernetes.io/part-of: backforge
spec:
  selector:
    app.kubernetes.io/name: backforge-api
  ports:
    - name: http
      port: 80
      targetPort: http
