apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backforge
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - api-rollout.yaml
  - worker-deployment.yaml
  - api-service.yaml
  - api-preview-service.yaml
  - api-canary-service.yaml
  - api-ingress.yaml
  - api-preview-ingress.yaml
  - api-hpa.yaml
  - worker-hpa.yaml
  - api-pdb.yaml
  - networkpolicy.yaml
  - service-monitor.yaml
  - prometheus-rule.yaml
  - rollout-analysis-template.yaml
